### ISSUE TITLE
Can you make a even shorter mapping?

### ISSUE THREAD

**Issue by jchain** [machakann/vim-sandwich#10]
First all, thank you so much for your plugin. I have replaced vim-surround with it. Happy.

But I have an itch on my back that really wish someone can make it happen:

Given a text string like [foo/bar], I'd like to move my cursor onto the first '[' and press 'sd' to remove the '[' and the matching ']'. And press 'sr(' to replace '[' with '(' and ']' with ')'. 

How do you like this idea?

**Comment by machakann** [comment]
Thank you for using!

Since the sandwich textobjects responses to a surrounding (like '[') under the cursor, I think `sdb` and `srb` works similar as you suggested, and you mean that you want to omit even also `b`. Right? It sounds nice idea to me, it will make faster to edit in some cases.

Vim-sandwich prepares some keymapping interfaces to make easier to define custom mappings. These ones will help you to do that. If you want to use the functionality with `sd` and `sr` key sequences, then add the description in your vimrc to replace default keymappings.
```vim
let g:sandwich_no_default_key_mappings = 1
nmap <silent> sd <Plug>(operator-sandwich-delete)<Plug>(textobj-sandwich-auto-a)
nmap <silent> sr <Plug>(operator-sandwich-replace)<Plug>(textobj-sandwich-auto-a)
```

Or making new alias mappings is also a choice, I prefer this.
```vim
nmap sx sdb
nmap sc srb
```

Vim-sandwich makes 's' starting keymappings with pain, these keymappings degrades (or I intentionally deactivated) built-in `s` command while vim-surround does not disturb it. However, due to the expense, we can use 's' starting keymappings freely. I think making shorthands is good strategy for us.

**Comment by jchain** [comment]
Thank you for the answer! I like the alias mappings, i.e., sx, sc.
