### ISSUE TITLE
Question operating pending mode.

### ISSUE THREAD

**Issue by windwp** [machakann/vim-sandwich#108]
Thank for create a good plugin.
I only have a question to how do you make vim change to mode (no) operation pending then it waitting to another key press.

It happen after i press `sr(` I see my status bar change to that mode and stay it.

I want to create a  function like that I hope you can give me some help.

**Comment by machakann** [comment]
Hello, @windwp. This is a difficult question since I don't know how much you are familiar with vim script, but I may be able to make some help and insight for you.

The key function is [`getchar()`](http://vimdoc.sourceforge.net/htmldoc/eval.html#getchar()); it tries to get input from the user and return the input as a number (or might be a string in some case). The MWE is something like the below.

```vim
function! Echo_input() abort
  let c0 = getchar()
  " c0 might be a string; for example, c0 is "\<Esc>" if user types <Esc> key.
  let c = type(c0) == v:t_number ? nr2char(c0) : c0
  if c is# "\<Esc>"
    return
  endif
  echo c
endfunction
nmap <silent> <Space> :<C-u>call Echo_input()<CR>
```

When you type <kbd><Space></kbd> in normal mode, vim waits for your next input and echo it. Actually, there are some options and a lot of trap on the use of `getchar()`. It would be better to start checking `:help getchar()`.

**Comment by machakann** [comment]
Oh, I forgot to tell you one thing. To be strict, that is not the operator-pending mode; you can easily make sure it as `:omap` command doesn't take effect. If you really want a real operator-pending mode, then what you should check is `:help g@` and `:help :map-operator`.

**Comment by windwp** [comment]
Thank 
function getchar() is  what i need on my plugin.
But I still don't understand why my statusbar always stay on that mode.
https://imgur.com/a/W7Lwbi7

**Comment by machakann** [comment]
That's because the `sr` is composed of an operator and a text-object. The `sr` is inherently a compound key mapping of the two; when you type `sr`, an operator (`g@`) and a text-object are triggered successively and the text-object calls the` getchar()` function to determine the text to replace. The `operatorfunc` is called after the target text determined to replace. That is, the timing `getchar()` calling is in between the operator and the `operatorfunc`. That's why it is in operator-pending mode. The `getchar()` itself doesn't relate to the mode.
```
          |                      sr                    |
          {operator}{textobj  (getchar)}{ operatorfunc }
[      normal      ][ operator-pending ][    normal    ]
```
