### ISSUE TITLE
Delete multiple types of function calls 

### ISSUE THREAD

**Issue by lsDrizzle** [machakann/vim-sandwich#112]
Magicchar-f is absolutely a wonderful feature. I notice that I can use `sandwich#magicchar#f#patterns` to define a function's pattern. 

I just wonder if I can define several types of function calls for one single file type (e.g., *.py). That will be useful because I may want to use `dsf` to change `foo[x]` into `x`, while I can change `foo(x)` into `x` in the same file. The former could be a dict in python.

In a more complex circumstance, I want to change `foo[i](x)` into `x`, where `foo` may be a list of functions. Is there a way to use `sandwich#magicchar#f#patterns` or something else to tell sandwich that they are all function calls that I hope to be deleted by magicchar-f? 

Thank you so much!

**Comment by machakann** [comment]
`g:sandwich_magicchar_f_patterns` is a list of patterns. Hence it naturally accepts multiple items. If you want to include two patterns globally, you can include them one by one.

```vim
let g:sandwich#magicchar#f#patterns = [
  \   {
  \     'header' : '\<\h\k*',
  \     'bra'    : '(',
  \     'ket'    : ')',
  \     'footer' : '',
  \   },
  \   {
  \     'header' : '\<\h\k*',
  \     'bra'    : '\[',
  \     'ket'    : '\]',
  \     'footer' : '',
  \   },
  \ ]
```

If you want to make filetype-specific patterns, use `b:sandwich_magicchar_f_patterns` instead of `g:sandwich#magicchar#f#patterns`.

The values for those four keys, "header", "bra", "ket", and "footer", is a regular expression pattern. Therefore, the pattern for texts like `foo[i](x)` is difficult since Vim's regular expression doesn't have any way to handle nested parentheses precisely. However, the non-greedy atom may work in many cases. So finally:

```vim
augroup sandwich-ft-python
  autocmd!
  autocmd Filetype python let b:sandwich_magicchar_f_patterns = [
  \   {
  \     'header' : '\<\h\k*',
  \     'bra'    : '(',
  \     'ket'    : ')',
  \     'footer' : '',
  \   },
  \   {
  \     'header' : '\<\h\k*',
  \     'bra'    : '\[',
  \     'ket'    : '\]',
  \     'footer' : '',
  \   },
  \   {
  \     'header' : '\<\h\k*\[.\{-}\]',
  \     'bra'    : '(',
  \     'ket'    : ')',
  \     'footer' : '',
  \   },
  \ ]
```

The latter item is stronger than the former; the third is prior to the second one.

See also [docs](https://github.com/machakann/vim-sandwich/blob/9e6340affe9f53c11a6975a5f50b9bf48adb692c/doc/sandwich.txt#L486-L536)

**Comment by lsDrizzle** [comment]
That's a very excellent and detailed reply. I read the docs before, and just didn't notice that it is a **list** of patterns. I thought it would be good enough if I can know how to add new patterns while preserving the existing ones, but you also gave me the regular expressions I need. It's very kind of you, and thanks a lot!
