### ISSUE TITLE
specifying delimiter before motion/textobj in normal mode

### ISSUE THREAD

**Issue by sunaku** [machakann/vim-sandwich#24]
Hello,

There's a discrepancy in the order of operands we must pass to sandwich, depending on the mode we are in:

* Already in visual mode: **`sa` + delimiter**
* Going into visual mode: `v` + motion/textobj + **`sa` + delimiter**
* Staying in normal mode: **`sa` + motion/textobj** + delimiter

The first two use cases are consistent: you type the sandwich operator and pass in a **delimiter**.  However, the third use case is different: you type the sandwich operator and pass in a **motion/textobj** (not a delimiter).  Due to this inconsistency, I often need to stop and think :scream: before performing the third use case. :disappointed: 

Is it possible to change the third use case to follow the same operand order as the first two?  I want to type:

* Staying in normal mode: **`sa` + delimiter** + motion/textobj

Thanks for your consideration.

> P.S.  Thanks for creating this most excellent plugin! :trophy: :+1: :heart_eyes_cat:

**Comment by machakann** [comment]
Yes, you can. Use `<Plug>(operator-sandwich-add-query1st)` instead of the default mapping. Add the line into your vimrc.

```vim
nmap sa <Plug>(operator-sandwich-add-query1st)
```

The mapping would work as you want, probably, but please note that it has a few (trivial) limitation [operator-sandwich.txt](https://github.com/machakann/vim-sandwich/blob/master/doc/operator-sandwich.txt#L1767).

**Comment by sunaku** [comment]
Perfect! :triumph: Thanks :+1:
