### ISSUE TITLE
Surrounding a part of xml tag

### ISSUE THREAD

**Issue by sudo-nice** [machakann/vim-sandwich#29]
Given some xml file with a line:
```
  <section id="n$1">
^^
Note these two leading spaces, it matters.
```
Stay on the number `1` and run `vsa}` or `sal}` to surrond the number with `{}`. Suddenly, the result is:
```
<section id="n${1">}
^^
Two spaces are gone.
```
I have no problem if either the line is not shifted to the right, or filetype for the buffer is not set.
Can you reproduce it?

**Comment by machakann** [comment]
Hi, I reproduced it, it is a bug. This is, as you mention, because of autoindent feature of Vim. I thought that this problem has been solved before, but it looks not... I will try again.

Temporary you can avoid the problem to add the lines in your vimrc.
```vim
augroup sandwich-ft-xml
  autocmd FileType xml call operator#sandwich#setlocal('all', 'all', 'indentkeys-', '{,}')
augroup END
```

If it gets better I will drop a news here!

**Comment by machakann** [comment]
OK, it should work as expected now. 

Note that the indent shift happens even if adding `{}` manually, so if you don't want it you need the above autocmd. Or change filetype setting for xml; remove `{` from `'indentkeys'` option.

**Comment by sudo-nice** [comment]
Thank you very much!
