### ISSUE TITLE
Sandwich recipes for (, [, and { with and without extra space?

### ISSUE THREAD

**Issue by telemachus** [machakann/vim-sandwich#33]
I've recently switched to vim-sandwich from vim-surround. I'm loving the additional features, but there's one thing I miss: in vim-surround `(`, `[`, and `{` are slightly different from `)`, `]`, and `}`. The left-hand versions surround the item with an extra space in addition to the brackets.

So, for example

    foo # ( results in ( foo )
    foo # ) results in (foo)
    etc.

I've added these personally with recipes like this:

    {'buns': ["( ", " )"], 'nesting': 1, 'match_syntax': 1, 'input': ['('] }

But I'm wondering if you would consider a patch to implement this in the plugin itself?

Thanks.

**Comment by machakann** [comment]
Hi @telemachus !

Actually I intentionally omitted the behavior because I never employed that when I used vim-surround. Sorry, though it is omitted based only on my preference, but I don't want to make other existing users confusing. I would not include it as a default recipes.

I can agree that someone who comes from vim-surround might worry about that. So I will add a page to wiki. Thank you for your comment!

**Comment by telemachus** [comment]
Not a problem at all. It's easy enough to add to personal recipes. Feel free to copy mine onto the wiki if you like. If I were you, I would put this on the same wiki page as other information about vim-surround. Thanks.

    
    let g:sandwich#recipes += [
    	\ {'buns': ["( ", " )"], 'nesting': 1, 'match_syntax': 1, 'input': ['('] },
    	\ {'buns': ["[ ", " ]"], 'nesting': 1, 'match_syntax': 1, 'input': ['['] },
    	\ {'buns': ["{ ", " }"], 'nesting': 1, 'match_syntax': 1, 'input': ['{'] },
    	\ ]

**Comment by machakann** [comment]
I will include them, Thank you.
