### ISSUE TITLE
Magicchar-f cannot delete surrounds if the inside text is a character

### ISSUE THREAD

**Issue by machakann** [machakann/vim-sandwich#47]
- OK
```
func(aa)   -- sdf -->  aa
```

- Not ok
```
func(a)  -- sdf --> func(a)
```

This might be a common problem of the use of `external` in delete/replace operators.

**Comment by miseran** [comment]
I may have found the issue. In `autoload/sandwich/magicchar/f.vim` on line 287:
```vim
        if !(bra_pos == ket_pos || (bra_pos[0] == ket_pos[0] && bra_pos[1]+1 == ket_pos[1]-1))
```
The last condition applies if the argument consists of a single character. If I understand the intent correctly, it should be `bra_pos[1]+1 == ket_pos[1]`, so that it applies to empty arguments. Or did I misunderstand something?

**Comment by machakann** [comment]
Sorry @miseran , I missed your comment, and yes! You are right!
Thanks, I will fix it.

**Comment by machakann** [comment]
Sorry, I forgot to push the fix. Thanks!
