### ISSUE TITLE
Help with linewise surrounds

### ISSUE THREAD

**Issue by anihm136** [machakann/vim-sandwich#87]
I think this should be a pretty obvious thing, but I'm not able to find any instruction on how to do linewise surrounds (similar to `yss` in surround.vim). I've even tried `0sa$`, but that omits the last character. I'm pretty sure there must be a way to do this, as it is provided in the surround.vim keymaps. Any suggestions?

**Comment by machakann** [comment]
Hello. I take a gif to make sure that wrap `    foo    bar` to `(    foo    bar)` with `0sa$`. You might mean you got `(    foo    ba)r`? It may be caused by any options, but I'm not sure at this moment. Can you make a minimum working vimrc? I believe `0sa$` should work.

![SS-sandwich](https://user-images.githubusercontent.com/480049/70685031-15f8c400-1ce3-11ea-8ab2-e367f3c5a266.gif)

---
Another way is to make a mapping, for example:

```vim
onoremap <SID>line :normal! ^vg_<CR>
nmap <silent> ss <Plug>(operator-sandwich-add)<SID>line
```
