### ISSUE TITLE
Text object for function arguments

### ISSUE THREAD

**Issue by joshuali925** [machakann/vim-sandwich#88]
Is it possible to create a text object for function arguments similar to [targets.vim](https://github.com/wellle/targets.vim#argument-text-objects)? 

If I just do this,

```vimL
let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
let g:sandwich#recipes += [{'buns': ['[\[{(,]', '[,\]})]'], 'input': ['a'], 'regex': 1}]
```

a `cisa` on `(a|bc[0], def)` would give me `(|], def)` instead of `(|, def)`.

I'm not too familiar with vim regex. Is it possible to implement it or should I use targets.vim along with vim-sandwich?

**Comment by machakann** [comment]
I think this kind of problem is difficult to handle with regular expressions, especially if an argument includes separators inside parentheses like `(abc(def, ghi), jkl)`, since regular expressions are not so good at handling nestings.

I expect it would be more satisfactory to use more particular plugins: [targets.vim](https://github.com/wellle/targets.vim), [vim-textobj-parameter](https://github.com/sgur/vim-textobj-parameter), [vim-swap](https://github.com/machakann/vim-swap).

**Comment by joshuali925** [comment]
Got it. Thanks for the quick response.
